version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: rust_app
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - "8080:8080"

volumes:
  redis_data:
