apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: BASE_URL
              value: "{{ .Values.env.BASE_URL }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: MAX_SLUG_LENGTH
              value: "{{ .Values.env.MAX_SLUG_LENGTH }}"
