replicaCount: 1

image:
  repository: url-shortener
  tag: latest
  pullPolicy: Never

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: url-shortener.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

env:
  BASE_URL: "http://localhost:8080"
  PORT: "8080"
  MAX_SLUG_LENGTH: "8"